// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvrrUa8pG6-YFOsaq08p9at7hhOF0OPE',
    appId: '1:61018032312:web:8dfcf057c50031b5920c4d',
    messagingSenderId: '61018032312',
    projectId: 'urbanride-c1184',
    authDomain: 'urbanride-c1184.firebaseapp.com',
    storageBucket: 'urbanride-c1184.appspot.com',
    measurementId: 'G-17XLWTHSZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1yjuMk32A0UnsL5RCG-I4reNVDHBiwA',
    appId: '1:61018032312:android:8df26a16a5f873c5920c4d',
    messagingSenderId: '61018032312',
    projectId: 'urbanride-c1184',
    storageBucket: 'urbanride-c1184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpR9NlXdw7661xyzfxYmudAFN0fgwqRkQ',
    appId: '1:61018032312:ios:34dd0de4b0365846920c4d',
    messagingSenderId: '61018032312',
    projectId: 'urbanride-c1184',
    storageBucket: 'urbanride-c1184.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpR9NlXdw7661xyzfxYmudAFN0fgwqRkQ',
    appId: '1:61018032312:ios:34dd0de4b0365846920c4d',
    messagingSenderId: '61018032312',
    projectId: 'urbanride-c1184',
    storageBucket: 'urbanride-c1184.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvrrUa8pG6-YFOsaq08p9at7hhOF0OPE',
    appId: '1:61018032312:web:71e4dd6d176928e2920c4d',
    messagingSenderId: '61018032312',
    projectId: 'urbanride-c1184',
    authDomain: 'urbanride-c1184.firebaseapp.com',
    storageBucket: 'urbanride-c1184.appspot.com',
    measurementId: 'G-W7XPJQVTKZ',
  );
}
